"""
This is a setup.py script generated by py2applet

Usage:
    rm -r build dist
    python2.7 setup.py py2app -A -s -d /Applications
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['app.py', 'images', 'src']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    name='DockWatts',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
