"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ["src/watts.py", "images/screenshot.png"]

setup(
    app=APP,
    options=dict(py2app=dict(
        plist=dict(
            CFBundleIdentifier="fi.annttu.DockWatts",
            LSBackgroundOnly=True,
        ),
    )),
    name='DockWatts',
    data_files=DATA_FILES,
    setup_requires=['py2app'],
)
